// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrkan6ilBbCm0qfVlwGjtjvWEatCLj8Lk',
    appId: '1:72064330630:web:85b7cdf8c7779601e51a07',
    messagingSenderId: '72064330630',
    projectId: 'expensetrackingapp-fa9da',
    authDomain: 'expensetrackingapp-fa9da.firebaseapp.com',
    storageBucket: 'expensetrackingapp-fa9da.firebasestorage.app',
    measurementId: 'G-L6HG2KF5F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA71BR2U-h3--DEOBNnlRPTEeNR5jqhYuc',
    appId: '1:72064330630:android:4cba52ba8c0fc2b8e51a07',
    messagingSenderId: '72064330630',
    projectId: 'expensetrackingapp-fa9da',
    storageBucket: 'expensetrackingapp-fa9da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_NXAi5adB4D3fbssFXxN-iDzCqs344dI',
    appId: '1:72064330630:ios:33726c0fc526bb82e51a07',
    messagingSenderId: '72064330630',
    projectId: 'expensetrackingapp-fa9da',
    storageBucket: 'expensetrackingapp-fa9da.firebasestorage.app',
    iosBundleId: 'com.example.expensetrackingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_NXAi5adB4D3fbssFXxN-iDzCqs344dI',
    appId: '1:72064330630:ios:33726c0fc526bb82e51a07',
    messagingSenderId: '72064330630',
    projectId: 'expensetrackingapp-fa9da',
    storageBucket: 'expensetrackingapp-fa9da.firebasestorage.app',
    iosBundleId: 'com.example.expensetrackingapp',
  );

}